(require 'ox-publish)

;; (org-publish "thoughts" t)

(defvar my/thoughts-dev t
  "Boolean flag to indicate development environment.")

(setq my/thoughts-dev nil)

(defconst my/thoughts-postamble
  (concat "<p class=\"author\">Author: %a</p>\n"
          "<p class=\"date\">Date: %d</p>\n"
          "<p class=\"creator\">Generated by: %c</p>\n"
          ))

(defconst my/thoughts-head
  (concat "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
          (my/thoughts-link
           "<link rel=\"stylesheet\" type=\"text/css\" href=\"%s\" />"
           "style.css")
          (my/thoughts-link
           "<script src=\"%s\"></script>"
           "bundle.js")))

(defun my/thoughts-link (format-str str)
  (format format-str (if my/thoughts-dev
                         (concat "/" str)
                       (concat "/thoughts/" str))))

(defun my/thoughts-preamble (_ignore)
  "Return a string containing a preable for the site."
  (my/thoughts-link "<div id=\"nav\"><a href=\"%s\">Home</a></div>"
                    ""))

(defvar my/thoughts-dir "/Users/johnhooks/Projects/elisp/thoughts/")

(defun my/root-link-follow (path)
  (org-open-file-with-emacs
   (concat my/thoughts-dir path)))

(my/root-link-follow "org/emacs/syntax.org")

(defun my/root-link-export (path desc format)
  (cond
   ((eq format 'html)
    (format "<a href=\"%s\">%s</a>"))))

(let* ((dir "/Users/johnhooks/Projects/elisp/thoughts/")
       (public (concat dir "docs/")))
  (setq org-publish-project-alist
        `(
          ("thoughts-org"
           ;; :html-link-home "thoughts"
           ;; :html-link-use-abs-url t
           :base-directory ,(concat dir "org/")
           :base-extension "org"
           :publishing-directory ,public
           :recursive t
           :publishing-function org-html-publish-to-html
           ;; Just the default for this project.
           :headline-levels 4
           ;; Generate sitemap.org automagically.
           :auto-sitemap t
           ;; Call it sitemap.org (it's the default).
           :sitemap-filename "sitemap.org"
           ;; With title 'Sitemap'.
           :sitemap-title "Sitemap"
           ;; Disable the inclusion of "Created by Org" in the postamble.
           ;; :with-creator nil
           ;; Disable the inclusion of "(your email)" in the postamble.
           ;; :with-email nil
           ;; Enable the inclusion of "Author: Your Name" in the postamble.
           ;; :with-author nil
           :auto-preamble t
           :auto-preamble t
           :html-head-include-default-style nil
           :html-head-include-scripts nil
           :html-head ,my/thoughts-head
           :html-preamble my/thoughts-preamble
           )
          ;; ("thoughts-static"
          ;;  :base-directory ,(concat dir "src/")
          ;;  :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
          ;;  :publishing-directory ,public
          ;;  :recursive t
          ;;  :publishing-function org-publish-attachment
          ;;  )
          ("thoughts"
           :components ("thoughts-org")
           )
          )
        org-export-with-section-numbers nil
        org-export-with-toc nil
        org-html-postamble t
        org-html-postamble-format
        `(("en" ,my/thoughts-postamble))
        ))
